// flow-typed signature: c9f796b32a12c6484d06fc754c18b434
// flow-typed version: <<STUB>>/pg_v^4.5.6/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg/lib/client' {
  declare module.exports: any;
}

declare module 'pg/lib/connection-parameters' {
  declare module.exports: any;
}

declare module 'pg/lib/connection' {
  declare module.exports: any;
}

declare module 'pg/lib/defaults' {
  declare module.exports: any;
}

declare module 'pg/lib/index' {
  declare module.exports: any;
}

declare module 'pg/lib/native/index' {
  declare module.exports: any;
}

declare module 'pg/lib/native/query' {
  declare module.exports: any;
}

declare module 'pg/lib/native/result' {
  declare module.exports: any;
}

declare module 'pg/lib/pool' {
  declare module.exports: any;
}

declare module 'pg/lib/query' {
  declare module.exports: any;
}

declare module 'pg/lib/result' {
  declare module.exports: any;
}

declare module 'pg/lib/type-overrides' {
  declare module.exports: any;
}

declare module 'pg/lib/utils' {
  declare module.exports: any;
}

declare module 'pg/script/create-test-tables' {
  declare module.exports: any;
}

declare module 'pg/script/dump-db-types' {
  declare module.exports: any;
}

declare module 'pg/script/list-db-types' {
  declare module.exports: any;
}

declare module 'pg/script/test-connection' {
  declare module.exports: any;
}

declare module 'pg/test/buffer-list' {
  declare module.exports: any;
}

declare module 'pg/test/cli' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/api-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/appname-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/array-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/big-simple-query-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/cancel-query-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/configuration-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/custom-types-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/empty-query-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/error-handling-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/force-native-with-envvar-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/heroku-pgpass-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/heroku-ssl-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/huge-numeric-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/json-type-parsing-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/no-data-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/no-row-result-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/notice-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/parse-int-8-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/prepared-statement-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/query-callback-error-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/query-column-names-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/query-error-handling-prepared-statement-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/query-error-handling-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/quick-disconnect-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/result-metadata-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/results-as-array-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/row-description-on-results-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/simple-query-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/ssl-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/timezone-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/transaction-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/type-coercion-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/client/type-parser-override-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/double-connection-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/ending-empty-pool-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/ending-pool-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/error-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/idle-timeout-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/max-connection-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/optional-config-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/single-connection-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection-pool/waiting-connection-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection/bound-command-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection/copy-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection/notification-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection/query-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/connection/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/integration/domain-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/130-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/131-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/199-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/507-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/600-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/675-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/699-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/787-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/882-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/gh-issues/981-tests' {
  declare module.exports: any;
}

declare module 'pg/test/integration/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/native/callback-api-tests' {
  declare module.exports: any;
}

declare module 'pg/test/native/connection-tests' {
  declare module.exports: any;
}

declare module 'pg/test/native/error-tests' {
  declare module.exports: any;
}

declare module 'pg/test/native/evented-api-tests' {
  declare module.exports: any;
}

declare module 'pg/test/native/missing-native' {
  declare module.exports: any;
}

declare module 'pg/test/native/stress-tests' {
  declare module.exports: any;
}

declare module 'pg/test/test-buffers' {
  declare module.exports: any;
}

declare module 'pg/test/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/cleartext-password-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/configuration-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/connection-string-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/early-disconnect-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/escape-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/md5-password-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/notification-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/prepared-statement-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/query-queue-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/result-metadata-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/simple-query-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/stream-and-query-error-interaction-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/client/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/unit/connection-parameters/creation-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/connection-parameters/environment-variable-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/connection/error-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/connection/inbound-parser-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/connection/outbound-sending-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/connection/startup-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/connection/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/unit/pool/basic-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/pool/timeout-tests' {
  declare module.exports: any;
}

declare module 'pg/test/unit/test-helper' {
  declare module.exports: any;
}

declare module 'pg/test/unit/utils-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg/lib/client.js' {
  declare module.exports: $Exports<'pg/lib/client'>;
}
declare module 'pg/lib/connection-parameters.js' {
  declare module.exports: $Exports<'pg/lib/connection-parameters'>;
}
declare module 'pg/lib/connection.js' {
  declare module.exports: $Exports<'pg/lib/connection'>;
}
declare module 'pg/lib/defaults.js' {
  declare module.exports: $Exports<'pg/lib/defaults'>;
}
declare module 'pg/lib/index.js' {
  declare module.exports: $Exports<'pg/lib/index'>;
}
declare module 'pg/lib/native/index.js' {
  declare module.exports: $Exports<'pg/lib/native/index'>;
}
declare module 'pg/lib/native/query.js' {
  declare module.exports: $Exports<'pg/lib/native/query'>;
}
declare module 'pg/lib/native/result.js' {
  declare module.exports: $Exports<'pg/lib/native/result'>;
}
declare module 'pg/lib/pool.js' {
  declare module.exports: $Exports<'pg/lib/pool'>;
}
declare module 'pg/lib/query.js' {
  declare module.exports: $Exports<'pg/lib/query'>;
}
declare module 'pg/lib/result.js' {
  declare module.exports: $Exports<'pg/lib/result'>;
}
declare module 'pg/lib/type-overrides.js' {
  declare module.exports: $Exports<'pg/lib/type-overrides'>;
}
declare module 'pg/lib/utils.js' {
  declare module.exports: $Exports<'pg/lib/utils'>;
}
declare module 'pg/script/create-test-tables.js' {
  declare module.exports: $Exports<'pg/script/create-test-tables'>;
}
declare module 'pg/script/dump-db-types.js' {
  declare module.exports: $Exports<'pg/script/dump-db-types'>;
}
declare module 'pg/script/list-db-types.js' {
  declare module.exports: $Exports<'pg/script/list-db-types'>;
}
declare module 'pg/script/test-connection.js' {
  declare module.exports: $Exports<'pg/script/test-connection'>;
}
declare module 'pg/test/buffer-list.js' {
  declare module.exports: $Exports<'pg/test/buffer-list'>;
}
declare module 'pg/test/cli.js' {
  declare module.exports: $Exports<'pg/test/cli'>;
}
declare module 'pg/test/integration/client/api-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/api-tests'>;
}
declare module 'pg/test/integration/client/appname-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/appname-tests'>;
}
declare module 'pg/test/integration/client/array-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/array-tests'>;
}
declare module 'pg/test/integration/client/big-simple-query-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/big-simple-query-tests'>;
}
declare module 'pg/test/integration/client/cancel-query-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/cancel-query-tests'>;
}
declare module 'pg/test/integration/client/configuration-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/configuration-tests'>;
}
declare module 'pg/test/integration/client/custom-types-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/custom-types-tests'>;
}
declare module 'pg/test/integration/client/empty-query-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/empty-query-tests'>;
}
declare module 'pg/test/integration/client/error-handling-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/error-handling-tests'>;
}
declare module 'pg/test/integration/client/force-native-with-envvar-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/force-native-with-envvar-tests'>;
}
declare module 'pg/test/integration/client/heroku-pgpass-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/heroku-pgpass-tests'>;
}
declare module 'pg/test/integration/client/heroku-ssl-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/heroku-ssl-tests'>;
}
declare module 'pg/test/integration/client/huge-numeric-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/huge-numeric-tests'>;
}
declare module 'pg/test/integration/client/json-type-parsing-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/json-type-parsing-tests'>;
}
declare module 'pg/test/integration/client/no-data-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/no-data-tests'>;
}
declare module 'pg/test/integration/client/no-row-result-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/no-row-result-tests'>;
}
declare module 'pg/test/integration/client/notice-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/notice-tests'>;
}
declare module 'pg/test/integration/client/parse-int-8-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/parse-int-8-tests'>;
}
declare module 'pg/test/integration/client/prepared-statement-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/prepared-statement-tests'>;
}
declare module 'pg/test/integration/client/query-callback-error-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/query-callback-error-tests'>;
}
declare module 'pg/test/integration/client/query-column-names-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/query-column-names-tests'>;
}
declare module 'pg/test/integration/client/query-error-handling-prepared-statement-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/query-error-handling-prepared-statement-tests'>;
}
declare module 'pg/test/integration/client/query-error-handling-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/query-error-handling-tests'>;
}
declare module 'pg/test/integration/client/quick-disconnect-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/quick-disconnect-tests'>;
}
declare module 'pg/test/integration/client/result-metadata-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/result-metadata-tests'>;
}
declare module 'pg/test/integration/client/results-as-array-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/results-as-array-tests'>;
}
declare module 'pg/test/integration/client/row-description-on-results-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/row-description-on-results-tests'>;
}
declare module 'pg/test/integration/client/simple-query-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/simple-query-tests'>;
}
declare module 'pg/test/integration/client/ssl-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/ssl-tests'>;
}
declare module 'pg/test/integration/client/test-helper.js' {
  declare module.exports: $Exports<'pg/test/integration/client/test-helper'>;
}
declare module 'pg/test/integration/client/timezone-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/timezone-tests'>;
}
declare module 'pg/test/integration/client/transaction-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/transaction-tests'>;
}
declare module 'pg/test/integration/client/type-coercion-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/type-coercion-tests'>;
}
declare module 'pg/test/integration/client/type-parser-override-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/client/type-parser-override-tests'>;
}
declare module 'pg/test/integration/connection-pool/double-connection-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/double-connection-tests'>;
}
declare module 'pg/test/integration/connection-pool/ending-empty-pool-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/ending-empty-pool-tests'>;
}
declare module 'pg/test/integration/connection-pool/ending-pool-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/ending-pool-tests'>;
}
declare module 'pg/test/integration/connection-pool/error-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/error-tests'>;
}
declare module 'pg/test/integration/connection-pool/idle-timeout-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/idle-timeout-tests'>;
}
declare module 'pg/test/integration/connection-pool/max-connection-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/max-connection-tests'>;
}
declare module 'pg/test/integration/connection-pool/optional-config-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/optional-config-tests'>;
}
declare module 'pg/test/integration/connection-pool/single-connection-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/single-connection-tests'>;
}
declare module 'pg/test/integration/connection-pool/test-helper.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/test-helper'>;
}
declare module 'pg/test/integration/connection-pool/waiting-connection-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection-pool/waiting-connection-tests'>;
}
declare module 'pg/test/integration/connection/bound-command-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection/bound-command-tests'>;
}
declare module 'pg/test/integration/connection/copy-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection/copy-tests'>;
}
declare module 'pg/test/integration/connection/notification-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection/notification-tests'>;
}
declare module 'pg/test/integration/connection/query-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/connection/query-tests'>;
}
declare module 'pg/test/integration/connection/test-helper.js' {
  declare module.exports: $Exports<'pg/test/integration/connection/test-helper'>;
}
declare module 'pg/test/integration/domain-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/domain-tests'>;
}
declare module 'pg/test/integration/gh-issues/130-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/130-tests'>;
}
declare module 'pg/test/integration/gh-issues/131-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/131-tests'>;
}
declare module 'pg/test/integration/gh-issues/199-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/199-tests'>;
}
declare module 'pg/test/integration/gh-issues/507-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/507-tests'>;
}
declare module 'pg/test/integration/gh-issues/600-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/600-tests'>;
}
declare module 'pg/test/integration/gh-issues/675-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/675-tests'>;
}
declare module 'pg/test/integration/gh-issues/699-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/699-tests'>;
}
declare module 'pg/test/integration/gh-issues/787-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/787-tests'>;
}
declare module 'pg/test/integration/gh-issues/882-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/882-tests'>;
}
declare module 'pg/test/integration/gh-issues/981-tests.js' {
  declare module.exports: $Exports<'pg/test/integration/gh-issues/981-tests'>;
}
declare module 'pg/test/integration/test-helper.js' {
  declare module.exports: $Exports<'pg/test/integration/test-helper'>;
}
declare module 'pg/test/native/callback-api-tests.js' {
  declare module.exports: $Exports<'pg/test/native/callback-api-tests'>;
}
declare module 'pg/test/native/connection-tests.js' {
  declare module.exports: $Exports<'pg/test/native/connection-tests'>;
}
declare module 'pg/test/native/error-tests.js' {
  declare module.exports: $Exports<'pg/test/native/error-tests'>;
}
declare module 'pg/test/native/evented-api-tests.js' {
  declare module.exports: $Exports<'pg/test/native/evented-api-tests'>;
}
declare module 'pg/test/native/missing-native.js' {
  declare module.exports: $Exports<'pg/test/native/missing-native'>;
}
declare module 'pg/test/native/stress-tests.js' {
  declare module.exports: $Exports<'pg/test/native/stress-tests'>;
}
declare module 'pg/test/test-buffers.js' {
  declare module.exports: $Exports<'pg/test/test-buffers'>;
}
declare module 'pg/test/test-helper.js' {
  declare module.exports: $Exports<'pg/test/test-helper'>;
}
declare module 'pg/test/unit/client/cleartext-password-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/cleartext-password-tests'>;
}
declare module 'pg/test/unit/client/configuration-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/configuration-tests'>;
}
declare module 'pg/test/unit/client/connection-string-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/connection-string-tests'>;
}
declare module 'pg/test/unit/client/early-disconnect-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/early-disconnect-tests'>;
}
declare module 'pg/test/unit/client/escape-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/escape-tests'>;
}
declare module 'pg/test/unit/client/md5-password-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/md5-password-tests'>;
}
declare module 'pg/test/unit/client/notification-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/notification-tests'>;
}
declare module 'pg/test/unit/client/prepared-statement-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/prepared-statement-tests'>;
}
declare module 'pg/test/unit/client/query-queue-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/query-queue-tests'>;
}
declare module 'pg/test/unit/client/result-metadata-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/result-metadata-tests'>;
}
declare module 'pg/test/unit/client/simple-query-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/simple-query-tests'>;
}
declare module 'pg/test/unit/client/stream-and-query-error-interaction-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/client/stream-and-query-error-interaction-tests'>;
}
declare module 'pg/test/unit/client/test-helper.js' {
  declare module.exports: $Exports<'pg/test/unit/client/test-helper'>;
}
declare module 'pg/test/unit/connection-parameters/creation-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/connection-parameters/creation-tests'>;
}
declare module 'pg/test/unit/connection-parameters/environment-variable-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/connection-parameters/environment-variable-tests'>;
}
declare module 'pg/test/unit/connection/error-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/connection/error-tests'>;
}
declare module 'pg/test/unit/connection/inbound-parser-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/connection/inbound-parser-tests'>;
}
declare module 'pg/test/unit/connection/outbound-sending-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/connection/outbound-sending-tests'>;
}
declare module 'pg/test/unit/connection/startup-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/connection/startup-tests'>;
}
declare module 'pg/test/unit/connection/test-helper.js' {
  declare module.exports: $Exports<'pg/test/unit/connection/test-helper'>;
}
declare module 'pg/test/unit/pool/basic-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/pool/basic-tests'>;
}
declare module 'pg/test/unit/pool/timeout-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/pool/timeout-tests'>;
}
declare module 'pg/test/unit/test-helper.js' {
  declare module.exports: $Exports<'pg/test/unit/test-helper'>;
}
declare module 'pg/test/unit/utils-tests.js' {
  declare module.exports: $Exports<'pg/test/unit/utils-tests'>;
}
